const nav=document.querySelectorAll('.nav-item'),pages=document.querySelectorAll('.page'),title=document.getElementById('pageTitle');
const titles={dashboard:'Good morning 👋',websites:'Websites',clients:'Clients',money:'Money',goals:'Goals',tools:'Tools'};
function go(page){pages.forEach(p=>p.classList.toggle('active',p.id===page));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===page));title.textContent=titles[page]||'Workspace';document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
nav.forEach(n=>n.addEventListener('click',()=>go(n.dataset.page)));
document.querySelectorAll('[data-page-jump]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.pageJump)));
document.getElementById('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const modal=document.getElementById('modal'),content=document.getElementById('modalContent');
function openModal(html){content.innerHTML=html;modal.classList.add('open');}
document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
function form(titleText,label,placeholder,buttonText='Save'){openModal('<h2>'+titleText+'</h2><p class="muted">Keep this simple for now. Your entries can become connected data later.</p><input placeholder="'+label+'"><input placeholder="'+placeholder+'"><div class="modal-actions"><button class="secondary" onclick="document.getElementById(\'modal\').classList.remove(\'open\')">Cancel</button><button class="primary" onclick="document.getElementById(\'modal\').classList.remove(\'open\')">'+buttonText+'</button></div>')}
document.getElementById('newSite').onclick=()=>form('Create a website','Business name','What does the business do?','Create draft');
document.getElementById('startBuilder').onclick=()=>form('AI Website Starter','Business name','Describe the business in one sentence','Generate structure');
document.getElementById('addClient').onclick=()=>form('Add a client','Client or business name','Project and expected value','Add client');
document.getElementById('addMoney').onclick=()=>form('Add transaction','Amount e.g. ₦5,000','Income, saving or expense','Add');
document.getElementById('addGoal').onclick=()=>form('New goal','Goal name','Target amount or outcome','Create goal');
document.getElementById('addTask').onclick=()=>form('Add task','Task name','When should it be done?','Add task');
document.getElementById('calcBtn').onclick=()=>openModal('<h2>Investment calculator</h2><p class="muted">Estimate compound growth.</p><input id="principal" type="number" placeholder="Starting amount"><input id="rate" type="number" placeholder="Annual rate %"><input id="years" type="number" placeholder="Years"><div class="modal-actions"><button class="primary" id="calculate">Calculate</button></div><div id="result" class="ai-answer"></div>');
document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='calculate'){let p=+document.getElementById('principal').value||0,r=(+document.getElementById('rate').value||0)/100,y=+document.getElementById('years').value||0;document.getElementById('result').textContent='Estimated value: ₦'+(p*Math.pow(1+r,y)).toLocaleString('en-NG',{maximumFractionDigits:0})}});
document.getElementById('checkBtn').onclick=()=>openModal('<h2>Quick checklist</h2><textarea rows="5" placeholder="Type tasks, one per line..."></textarea><div class="modal-actions"><button class="primary" onclick="document.getElementById(\'modal\').classList.remove(\'open\')">Create checklist</button></div>');
let timer,secs=1500;document.getElementById('timerBtn').onclick=()=>{if(timer)return;const b=document.getElementById('timerBtn');timer=setInterval(()=>{secs--;b.textContent=Math.floor(secs/60)+':'+String(secs%60).padStart(2,'0');if(secs<=0){clearInterval(timer);timer=null;secs=1500;b.textContent='25:00 focus'}},1000)};
document.getElementById('aiBtn').onclick=()=>{const v=document.getElementById('aiInput').value.toLowerCase();let a=v.includes('money')?'Pick one income task: make a simple business landing page, message 3 potential clients, and keep part of any payment you receive.':v.includes('hour')?'Use your time in one focused block: 45 minutes learning, 60 minutes building, then 15 minutes contacting a potential client.':'Start with the highest-impact unfinished task, give it 45 focused minutes, then review what changed.';document.getElementById('aiAnswer').textContent=a};
